/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inmersiontracker.GUI;

import inmersiontracker.Code.LogEntry;
import inmersiontracker.Code.MyArrayList;

/**
 *
 * @author felip
 */
public class InmersTrack extends javax.swing.JFrame {

    /**
     * Creates new form InmersTrack
     */
    public InmersTrack() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        LandingPage = new javax.swing.JPanel();
        Welcome_text = new javax.swing.JLabel();
        Language_Selection = new javax.swing.JComboBox<>();
        Language_select_label = new javax.swing.JLabel();
        btn_main_menu = new javax.swing.JButton();
        LogEntry = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Description_LE = new javax.swing.JTextField();
        LogEntryButton_LE = new javax.swing.JButton();
        Success_LE = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ActivityComboBox_LE = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        Duration_LE = new javax.swing.JTextField();
        General_View = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LogTimeButton_GV = new javax.swing.JToggleButton();
        StatsButton_GV = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setLayout(new java.awt.CardLayout());

        LandingPage.setBackground(new java.awt.Color(204, 255, 255));

        Welcome_text.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Welcome_text.setText("Welcome, Felipe");

        Language_Selection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Japanese", "Spanish", "Chinese", "English", "French", "Korean", "Portuguese", " " }));
        Language_Selection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Language_SelectionActionPerformed(evt);
            }
        });

        Language_select_label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Language_select_label.setText("Select the language:");

        btn_main_menu.setText("Enter");
        btn_main_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_main_menuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LandingPageLayout = new javax.swing.GroupLayout(LandingPage);
        LandingPage.setLayout(LandingPageLayout);
        LandingPageLayout.setHorizontalGroup(
            LandingPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LandingPageLayout.createSequentialGroup()
                .addGap(0, 431, Short.MAX_VALUE)
                .addComponent(Welcome_text, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
            .addGroup(LandingPageLayout.createSequentialGroup()
                .addGroup(LandingPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LandingPageLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(LandingPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Language_Selection, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Language_select_label)))
                    .addGroup(LandingPageLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(btn_main_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LandingPageLayout.setVerticalGroup(
            LandingPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LandingPageLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(Welcome_text, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addComponent(Language_select_label)
                .addGap(18, 18, 18)
                .addComponent(Language_Selection, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btn_main_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        Background.add(LandingPage, "card2");

        LogEntry.setBackground(new java.awt.Color(102, 204, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Description (Optional)");

        LogEntryButton_LE.setText("Log Entry");
        LogEntryButton_LE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogEntryButton_LEActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel2.setText("Log Entry");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Activity Done");

        ActivityComboBox_LE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Listening", "Watching", "Reading", "Grammar", "Class" }));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Duration (Minutes)");

        javax.swing.GroupLayout LogEntryLayout = new javax.swing.GroupLayout(LogEntry);
        LogEntry.setLayout(LogEntryLayout);
        LogEntryLayout.setHorizontalGroup(
            LogEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogEntryLayout.createSequentialGroup()
                .addGroup(LogEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LogEntryLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2))
                    .addGroup(LogEntryLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(LogEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addGroup(LogEntryLayout.createSequentialGroup()
                                .addGroup(LogEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ActivityComboBox_LE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(123, 123, 123)
                                .addGroup(LogEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Description_LE)))
                            .addGroup(LogEntryLayout.createSequentialGroup()
                                .addComponent(Duration_LE, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LogEntryButton_LE, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)))))
                .addContainerGap(292, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogEntryLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Success_LE, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LogEntryLayout.setVerticalGroup(
            LogEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogEntryLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(56, 56, 56)
                .addGroup(LogEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(LogEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Description_LE, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ActivityComboBox_LE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LogEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Duration_LE, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LogEntryButton_LE, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Success_LE, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                .addContainerGap())
        );

        Background.add(LogEntry, "card3");

        General_View.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("dd/mm/yyyy");

        LogTimeButton_GV.setText("Log Entry");
        LogTimeButton_GV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogTimeButton_GVActionPerformed(evt);
            }
        });

        StatsButton_GV.setText("Stats");

        javax.swing.GroupLayout General_ViewLayout = new javax.swing.GroupLayout(General_View);
        General_View.setLayout(General_ViewLayout);
        General_ViewLayout.setHorizontalGroup(
            General_ViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(General_ViewLayout.createSequentialGroup()
                .addGroup(General_ViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(General_ViewLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(General_ViewLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(General_ViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LogTimeButton_GV, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(StatsButton_GV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(532, Short.MAX_VALUE))
        );
        General_ViewLayout.setVerticalGroup(
            General_ViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(General_ViewLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(131, 131, 131)
                .addComponent(LogTimeButton_GV, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(StatsButton_GV, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        Background.add(General_View, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Language_SelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Language_SelectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Language_SelectionActionPerformed

    private void btn_main_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_main_menuActionPerformed
        LandingPage.setVisible(false);
        General_View.setVisible(true);
    }//GEN-LAST:event_btn_main_menuActionPerformed

    private void LogTimeButton_GVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogTimeButton_GVActionPerformed
        General_View.setVisible(false);
        LogEntry.setVisible(true);
    }//GEN-LAST:event_LogTimeButton_GVActionPerformed

    private void LogEntryButton_LEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogEntryButton_LEActionPerformed
        try{
            MyArrayList list = new MyArrayList();

            String act = ActivityComboBox_LE.getSelectedItem().toString();
            String minutes = Duration_LE.getText();
            int mins = Integer.parseInt(minutes);

            //        try{
                //            int mins = Integer.parseInt(minutes);
                //        } catch(Exception e){
                //            //Do sum
                //        }
            //
            String desc = Description_LE.getText();

            LogEntry Entry = new LogEntry(mins, desc, act);

            list.add(Entry);
            
            Duration_LE.setText("");
            Description_LE.setText("");

            LogEntry.setVisible(false);
            General_View.setVisible(true);
        }catch(Exception e){
            Success_LE.setText("Log Entry failed! " + e);
        }
    }//GEN-LAST:event_LogEntryButton_LEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InmersTrack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InmersTrack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InmersTrack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InmersTrack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InmersTrack().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ActivityComboBox_LE;
    private javax.swing.JPanel Background;
    private javax.swing.JTextField Description_LE;
    private javax.swing.JTextField Duration_LE;
    private javax.swing.JPanel General_View;
    private javax.swing.JPanel LandingPage;
    private javax.swing.JComboBox<String> Language_Selection;
    private javax.swing.JLabel Language_select_label;
    private javax.swing.JPanel LogEntry;
    private javax.swing.JButton LogEntryButton_LE;
    private javax.swing.JToggleButton LogTimeButton_GV;
    private javax.swing.JButton StatsButton_GV;
    private javax.swing.JLabel Success_LE;
    private javax.swing.JLabel Welcome_text;
    private javax.swing.JButton btn_main_menu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
